set nocompatible
syntax on
set showmode
set showcmd
set encoding=utf-8
set t_Co=256
filetype indent on
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set number
set norelativenumber
set cursorline
set wrap
set linebreak
set wrapmargin=2
set laststatus=2
set ruler
set showmatch
set noerrorbells
set autoread
